### ISSUE TITLE
Buildarr `secrets.json` is submitted to version control

### ISSUE THREAD

**Issue by Callum027** [ProfMoo/home#13]
Hi there,

I couldn't help but browse your setup (since it is on a public repository), and noticed that Buildarr's `secrets.json` file has been submitted to version control..

Buildarr's `secrets.json` file is generated while Buildarr is running, and contains caches for your API keys for your local instances (which are presumably not accessible from the public Internet, but it's better to be safe than sorry). It is better to think of this as a temporary file that should not be submitted to version control.

**Comment by Callum027** [comment]
I also recommend changing your Prowlarr instance's API key using the UI, and updating the Prowlarr configuration file accordingly.

**Comment by ProfMoo** [comment]
@Callum027 Thanks for visiting 😄. Yes, I definitely agree. The Arr secret configuration practices in this repo are *lacking* to say the least. I intend to clean that up next time I'm working on the Arr apps.

I need to cleanup my secret handling in general via sops 😅

**Comment by ProfMoo** [comment]
Solved [here](https://github.com/ProfMoo/home/blob/master/kubernetes/homelab/apps/media/buildarr/secrets/buildarr.secret.sops.yaml) 😄.
